<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__firstName</name>
   <tag></tag>
   <elementGuidId>e00fa865-f465-4e93-89d8-fd9e36a6fefa</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='firstName']</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;firstName&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>33f361f5-f77f-45c9-ac04-4547c7b34c8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9005918c-0a52-4e6a-aec4-f8cfc3811f0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fs-mask container mt-0 mb-2 h-14 py-4 appearance-none box-border px-5 border rounded focus:outline-none focus:z-10 focus:ring-pop-orange focus:border-pop-orange border-pop-gray-200</value>
      <webElementGuid>4eb0f241-6aa5-4828-94d4-6e0cf03445d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>firstName</value>
      <webElementGuid>03cc6220-572a-4bf5-923d-01450926afa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;login flex flex-col items-center pt-6 sm:pt-20 p-4&quot;]/div[@class=&quot;pop-card box-border p-4 bg-white rounded-lg shadow mobile-l:py-8 mobile-l:px-6 w-full max-w-lg mt-6 margin-auto mobile-l:px-8&quot;]/form[@class=&quot;mt-12&quot;]/div[@class=&quot;name-inputs flex flex-col space-y-4 sm:space-y-0 sm:flex-row sm:space-x-4&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;input-field relative&quot;]/input[@class=&quot;fs-mask container mt-0 mb-2 h-14 py-4 appearance-none box-border px-5 border rounded focus:outline-none focus:z-10 focus:ring-pop-orange focus:border-pop-orange border-pop-gray-200&quot;]</value>
      <webElementGuid>b8fb7955-0270-46d6-a413-31895a8db0e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='firstName']</value>
      <webElementGuid>2a97b803-a79c-4363-928b-bea6de469594</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/form/div/div/div/input</value>
      <webElementGuid>8cc35efc-79db-4ab6-83b2-ee582930ede8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a226c58e-08d0-4e49-b0c1-fc3c82ce05c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'firstName']</value>
      <webElementGuid>cfd84e2a-34b2-466e-a155-5d5c71f9b8f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
