<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__address</name>
   <tag></tag>
   <elementGuidId>43273bee-bc16-491d-949a-0d470287a6d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='address']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;address&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>73233ebe-f120-4554-a17f-1dc6e7bd1561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e2f8b03f-408a-4401-a40f-39c44d1466f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fs-mask container mt-0 mb-2 h-14 py-4 appearance-none box-border px-5 border rounded focus:outline-none focus:z-10 focus:ring-pop-orange focus:border-pop-orange border-pop-gray-200</value>
      <webElementGuid>e57f0427-5a40-4c4c-ae53-6df5c5b72c52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>857c7cce-6da2-4506-80bf-77d7b67d74af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address</value>
      <webElementGuid>bf6bf775-ea9f-4e0b-879c-bbd663427e56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;new-property&quot;]/div[@class=&quot;new-property flex flex-col items-center pt-6 sm:pt-20 p-4&quot;]/div[@class=&quot;pop-card box-border p-4 bg-white rounded-lg shadow mobile-l:py-8 mobile-l:px-6 w-full max-w-2xl mt-6 margin-auto mobile-l:px-8&quot;]/form[1]/fieldset[1]/div[@class=&quot;property-details&quot;]/div[@class=&quot;form-content mt-10&quot;]/div[@class=&quot;flex flex-col sm:flex-row sm:space-x-4&quot;]/div[@class=&quot;input-address relative sm:mb-4 flex-grow&quot;]/div[@class=&quot;container mt-0 sm:mb-2&quot;]/div[@class=&quot;input-field relative&quot;]/input[@class=&quot;fs-mask container mt-0 mb-2 h-14 py-4 appearance-none box-border px-5 border rounded focus:outline-none focus:z-10 focus:ring-pop-orange focus:border-pop-orange border-pop-gray-200&quot;]</value>
      <webElementGuid>29158bf6-625a-413f-8b89-681780eceec6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='address']</value>
      <webElementGuid>f61675ec-234a-47d8-a7b9-e2f043ff5e34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/form/fieldset/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>87c6fb9d-7c96-4505-8ac4-0025708106fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b66cf98e-6e48-4620-9b45-16407e6440e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'address']</value>
      <webElementGuid>b93ffa73-5c0d-4554-8e46-a2aa336cda07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
