<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_property-address1</name>
   <tag></tag>
   <elementGuidId>9be1e1b2-0cf4-4d8b-9877-f83c587da709</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/form/fieldset/div[2]/div/div/div/div[2]/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>83b6e86f-0ccd-4afe-a941-797d8c7ad13a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-4 hover:bg-lightBlueGray cursor-pointer</value>
      <webElementGuid>b07928e1-147a-4df1-aae9-50eefea332cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1585 Charleston Rd, Mountain View, CA, USA</value>
      <webElementGuid>86f33643-e67a-44b8-87a9-436b44156e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;new-property&quot;]/div[@class=&quot;new-property flex flex-col items-center pt-6 sm:pt-20 p-4&quot;]/div[@class=&quot;pop-card box-border p-4 bg-white rounded-lg shadow mobile-l:py-8 mobile-l:px-6 w-full max-w-2xl mt-6 margin-auto mobile-l:px-8&quot;]/form[1]/fieldset[1]/div[@class=&quot;property-details&quot;]/div[@class=&quot;form-content mt-10&quot;]/div[@class=&quot;flex flex-col sm:flex-row sm:space-x-4&quot;]/div[@class=&quot;input-address relative sm:mb-4 flex-grow&quot;]/div[@class=&quot;suggestions absolute z-10 bg-white shadow-sm w-full border border-pop-gray-100&quot;]/p[@class=&quot;p-4 hover:bg-lightBlueGray cursor-pointer&quot;]</value>
      <webElementGuid>dbb50ec8-b6fc-40f9-804f-536852005e3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/form/fieldset/div[2]/div/div/div/div[2]/p</value>
      <webElementGuid>d77b5996-ae3e-4f21-aba2-41676aaaf5b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::p[1]</value>
      <webElementGuid>d1c968cb-b59c-4ba6-a5f2-5d8bf8fd65b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Property details'])[1]/following::p[3]</value>
      <webElementGuid>fa024025-8624-49a1-9c42-ee1cbe5af9e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::p[6]</value>
      <webElementGuid>32bd9b8a-43d3-4bf3-bb8f-9d871a7ee3f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/preceding::p[7]</value>
      <webElementGuid>b9afc125-e605-40b3-95eb-145b6a8dd7ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1585 Charleston Rd, Mountain View, CA, USA']/parent::*</value>
      <webElementGuid>7d3f0414-0f67-4116-b837-ecaf59bea7b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p</value>
      <webElementGuid>3fab8cbb-1267-448f-bbf5-7af4a200286f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '1585 Charleston Rd, Mountain View, CA, USA' or . = '1585 Charleston Rd, Mountain View, CA, USA')]</value>
      <webElementGuid>ae91a47e-7200-4993-9324-84ef30922eb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
