<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_lease-length</name>
   <tag></tag>
   <elementGuidId>33c892c8-9be8-48bf-a079-4a669db6ef04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='leaseLength']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;leaseLength&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9d998bf8-10dd-4a1a-a7b7-a372a07d0c35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>leaseLength</value>
      <webElementGuid>1849275f-e772-4eb7-bf7b-2aaa4510908e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-select bg-white focus:outline-none h-14 py-4 px-5 text-base border focus:ring-pop-orange focus:border-pop-orange border-pop-gray-200</value>
      <webElementGuid>6951713c-7c9d-4b23-9432-70455a919529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select lease length6 Months9 Months12 Months18 Months24 Months</value>
      <webElementGuid>8b5004e5-c828-4f86-b382-88ca5bfad370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;new-property&quot;]/div[@class=&quot;new-property flex flex-col items-center pt-6 sm:pt-20 p-4&quot;]/div[@class=&quot;pop-card box-border p-4 bg-white rounded-lg shadow mobile-l:py-8 mobile-l:px-6 w-full max-w-2xl mt-6 margin-auto mobile-l:px-8&quot;]/form[1]/fieldset[1]/div[@class=&quot;lease-details&quot;]/div[@class=&quot;form-content mt-10&quot;]/div[@class=&quot;name-inputs flex flex-col sm:flex-row sm:space-x-4 mb-6&quot;]/div[@class=&quot;input-select-wrapper mt-0 mb-2 flex-1&quot;]/div[@class=&quot;relative&quot;]/select[@class=&quot;input-select bg-white focus:outline-none h-14 py-4 px-5 text-base border focus:ring-pop-orange focus:border-pop-orange border-pop-gray-200&quot;]</value>
      <webElementGuid>c7d448a3-1b61-4786-94ad-e80d65d3c8a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='leaseLength']</value>
      <webElementGuid>54d57ee2-a3d2-4e78-b306-964507c9dbd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/form/fieldset/div[2]/div/div/div[2]/div/select</value>
      <webElementGuid>20679e79-b446-4e1b-a8ec-ed1a42158dee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::select[1]</value>
      <webElementGuid>0f79908b-cf19-4562-b658-7a61f03b8191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::select[1]</value>
      <webElementGuid>218875f7-910a-404c-b6b3-627363da1d42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/preceding::select[1]</value>
      <webElementGuid>9f9ba57f-3b11-44a1-aa66-dfbd7dbac539</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>6b5afbb8-d12e-4a8b-b023-4dc035c9d09f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'leaseLength' and (text() = 'Select lease length6 Months9 Months12 Months18 Months24 Months' or . = 'Select lease length6 Months9 Months12 Months18 Months24 Months')]</value>
      <webElementGuid>31f68197-5609-47f8-b65e-778557187c89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
